# Generated by Django 5.0.1 on 2024-01-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="mark_done",
            field=models.BooleanField(default=False, verbose_name="Completed"),
        ),
    ]
