# Generated by Django 5.0.1 on 2024-02-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0002_alter_task_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="mark_done",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.TextField(default="New", verbose_name="status"),
        ),
    ]
