# Generated by Django 5.0.1 on 2024-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0003_remove_task_mark_done_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="section_position",
            field=models.IntegerField(default=-1, verbose_name="Section Index"),
        ),
    ]
