# Generated by Django 5.0.1 on 2024-02-16 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0004_task_section_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="section_position",
        ),
    ]
