# Generated by Django 5.0.1 on 2024-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0005_remove_task_section_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="display_order",
            field=models.IntegerField(default=-1, verbose_name="Section Index"),
        ),
    ]
