# Generated by Django 5.0.1 on 2024-01-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProjectGroup", "0003_alter_projectmember_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
