# Generated by Django 5.0.1 on 2024-02-01 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProjectGroup", "0009_alter_projectgroup_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmembership",
            name="member",
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="member",
            field=models.ManyToManyField(
                null=True, related_name="membership_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
