# Generated by Django 5.0.1 on 2024-02-01 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProjectGroup", "0010_remove_projectmembership_member_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmembership",
            name="member",
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User ID",
            ),
        ),
    ]
