# Generated by Django 5.0.1 on 2024-01-06 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Subtask", "0001_initial"),
        ("Task", "0002_task_mark_done"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User ID",
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="Task.task",
                verbose_name="Task",
            ),
        ),
    ]
